# Generated by Django 4.2.5 on 2023-12-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='identificador',
        ),
    ]
