# Generated by Django 4.2.5 on 2024-01-23 15:56

import Aplicaciones.bbdd.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0004_mensajedirecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Título')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to=Aplicaciones.bbdd.models.user_directory_path, verbose_name='Foto')),
                ('caption', models.CharField(max_length=10000, verbose_name='Caption')),
                ('posted', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='bbdd.tag', verbose_name='Tags')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(blank=True, max_length=50, null=True)),
                ('lasT_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('bio', models.TextField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto de perfil')),
                ('favorite', models.ManyToManyField(to='bbdd.post')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
    ]
