# Generated by Django 4.2.5 on 2024-02-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbdd', '0006_sala'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
